# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "16f857752a7f7bd70afca5b39cb6abf2"
name = "eyejack-mobileapp"
handle = "eyejack-mobileapp"
application_url = "http://localhost:3000/"
embedded = true

[build]
include_config_on_deploy = true

[webhooks]
api_version = "2025-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products,write_products,read_collections,read_orders,write_orders,read_customers,write_customers,read_inventory,write_inventory,read_cart_transforms,write_cart_transforms"

[auth]
redirect_urls = [ "http://localhost:3000/api/auth" ]

[pos]
embedded = false
